# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver001.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QApplication, QMainWindow


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.show()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(807, 618)
        self.setStyleSheet("background-color: rgb(37, 37, 38);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setMinimumSize(QtCore.QSize(0, 60))
        self.gridWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.gridWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridWidget.setStyleSheet("background-color: rgb(45, 45, 48);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_pwd = QtWidgets.QLabel(self.gridWidget)
        self.lab_pwd.setStyleSheet("color:rgb(255, 255, 255)")
        self.lab_pwd.setObjectName("lab_pwd")
        self.gridLayout.addWidget(self.lab_pwd, 0, 5, 1, 1)
        self.btn_dirpath = QtWidgets.QPushButton(self.gridWidget)
        self.btn_dirpath.setMinimumSize(QtCore.QSize(50, 10))
        self.btn_dirpath.setMaximumSize(QtCore.QSize(50, 25))
        self.btn_dirpath.setStyleSheet("background-color:rgb(255, 255, 255); color:rgb(0, 0, 0)")
        self.btn_dirpath.setObjectName("btn_dirpath")
        self.gridLayout.addWidget(self.btn_dirpath, 0, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_paintbrush = QtWidgets.QPushButton(self.gridWidget)
        self.btn_paintbrush.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_paintbrush.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_paintbrush.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0);border-radius: 6 ; border : 1px solid black")
        self.btn_paintbrush.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/iconmonstr-paintbrush-1-240.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icon/iconmonstr-paintbrush-1-240 - ON.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_paintbrush.setIcon(icon)
        self.btn_paintbrush.setIconSize(QtCore.QSize(16, 16))
        self.btn_paintbrush.setCheckable(True)
        self.btn_paintbrush.setObjectName("btn_paintbrush")
        self.horizontalLayout.addWidget(self.btn_paintbrush)
        self.btn_floodfill = QtWidgets.QPushButton(self.gridWidget)
        self.btn_floodfill.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_floodfill.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_floodfill.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0);border-radius: 6 ; border : 1px solid black")
        self.btn_floodfill.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/iconmonstr-paint-bucket-10-240.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("icon/iconmonstr-paint-bucket-10-240 - ON.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_floodfill.setIcon(icon1)
        self.btn_floodfill.setCheckable(True)
        self.btn_floodfill.setObjectName("btn_floodfill")
        self.horizontalLayout.addWidget(self.btn_floodfill)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_test = QtWidgets.QPushButton(self.gridWidget)
        self.btn_test.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_test.setMaximumSize(QtCore.QSize(50, 20))
        self.btn_test.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0)")
        self.btn_test.setObjectName("btn_test")
        self.horizontalLayout.addWidget(self.btn_test)
        self.le_test = QtWidgets.QLineEdit(self.gridWidget)
        self.le_test.setMaximumSize(QtCore.QSize(50, 20))
        self.le_test.setStyleSheet("color:rgb(255, 255, 255)")
        self.le_test.setObjectName("le_test")
        self.horizontalLayout.addWidget(self.le_test)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.gridWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.horizontalGroupBox_2.setFont(font)
        self.horizontalGroupBox_2.setStyleSheet("border-width: 0px; border-style: solid")
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_color_print = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.lab_color_print.setMinimumSize(QtCore.QSize(30, 30))
        self.lab_color_print.setMaximumSize(QtCore.QSize(30, 30))
        self.lab_color_print.setText("")
        self.lab_color_print.setObjectName("lab_color_print")
        self.horizontalLayout_2.addWidget(self.lab_color_print)
        self.btn_color_1 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_1.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_1.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_1.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_1.setText("")
        self.btn_color_1.setObjectName("btn_color_1")
        self.horizontalLayout_2.addWidget(self.btn_color_1)
        self.btn_color_2 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_2.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_2.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_2.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_2.setText("")
        self.btn_color_2.setObjectName("btn_color_2")
        self.horizontalLayout_2.addWidget(self.btn_color_2)
        self.btn_color_3 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_3.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_3.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_3.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_3.setText("")
        self.btn_color_3.setObjectName("btn_color_3")
        self.horizontalLayout_2.addWidget(self.btn_color_3)
        self.btn_color_4 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_4.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_4.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_4.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_4.setText("")
        self.btn_color_4.setObjectName("btn_color_4")
        self.horizontalLayout_2.addWidget(self.btn_color_4)
        self.btn_color_5 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_5.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_5.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_5.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_5.setText("")
        self.btn_color_5.setObjectName("btn_color_5")
        self.horizontalLayout_2.addWidget(self.btn_color_5)
        self.btn_color_6 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_6.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_6.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_6.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_6.setText("")
        self.btn_color_6.setObjectName("btn_color_6")
        self.horizontalLayout_2.addWidget(self.btn_color_6)
        self.btn_color_7 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_7.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_7.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_7.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_7.setText("")
        self.btn_color_7.setObjectName("btn_color_7")
        self.horizontalLayout_2.addWidget(self.btn_color_7)
        self.btn_color_8 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_8.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_8.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_8.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_8.setText("")
        self.btn_color_8.setObjectName("btn_color_8")
        self.horizontalLayout_2.addWidget(self.btn_color_8)
        self.btn_color_9 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_9.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_9.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_9.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_9.setText("")
        self.btn_color_9.setObjectName("btn_color_9")
        self.horizontalLayout_2.addWidget(self.btn_color_9)
        self.btn_color_10 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_color_10.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_color_10.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_color_10.setStyleSheet("background-color:rgb(255, 255, 255) ; color:rgb(0, 0, 0); border-radius: 6 ; border : 0px solid black")
        self.btn_color_10.setText("")
        self.btn_color_10.setObjectName("btn_color_10")
        self.horizontalLayout_2.addWidget(self.btn_color_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.horizontalGroupBox_2, 1, 0, 1, 6)
        self.gridLayout_2.addWidget(self.gridWidget, 0, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tableWidget.setStyleSheet("background-color: rgb(45, 45, 48);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 1, 1, 1)
        self.widget = myWindow()
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 2, 0, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        self.btn_test.clicked.connect(self.btn_test_clicked)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_pwd.setText(_translate("MainWindow", "TextLabel"))
        self.btn_dirpath.setText(_translate("MainWindow", "Path"))
        self.btn_test.setText(_translate("MainWindow", "Test"))
        self.le_test.setText(_translate("MainWindow", "2.jpg"))

    def btn_test_clicked(self):
        self.widget.changeImageTool("drawing")
        self.widget.changeDrawingColor((100, 100, 0))
        self.widget.changeDrawingSize(1)
        self.widget.inputImage(self.le_test.text())
        self.widget.imageReprint()

    def btn_dirpath_clicked(self):
        fname = QFileDialog.getExistingDirectory(self.MainWindow_M, 'Open file', './')
        print(fname)

    def btn_color_1_clicked(self):
        pass

    def btn_color_2_clicked(self):
        pass

    def btn_color_3_clicked(self):
        pass

    def btn_color_4_clicked(self):
        pass

    def btn_color_5_clicked(self):
        pass

    def btn_color_6_clicked(self):
        pass

    def btn_color_7_clicked(self):
        pass

    def btn_color_8_clicked(self):
        pass

    def btn_color_9_clicked(self):
        pass

    def mousePressEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
            print("Main Point")

from test3 import myWindow

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ex = Ui_MainWindow()
    sys.exit(app.exec_())

